# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MuscuApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MuscuApp
  pod 'React', path: '../node_modules/react-native', subspecs: [
    'ART',
  ]

  target 'MuscuAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MuscuApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MuscuApp-tvOS

  target 'MuscuApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
